CREATE TABLE IF NOT EXISTS person(
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    fullname text NOT NULL CHECK (fullname <> ''),
    birth date NOT NULL
);

INSERT INTO person( fullname, birth)
    VALUES('Juan Jaminton Yate', '1991-01-28');

INSERT INTO person( fullname, birth)
    VALUES('Elizabeth Guerrero Hernandez', '1992-06-04');