CREATE TABLE IF NOT EXISTS personas(
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    fullname text NOT NULL CHECK (fullname <> ''),
    birth date NOT NULL,
    createdAt TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updatedAt TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

INSERT INTO personas( fullname, birth)
    VALUES('Juan Jaminton Yate', '1991-01-28');

INSERT INTO personas( fullname, birth)
    VALUES('Elizabeth Guerrero Hernandez', '1992-06-04');